### ISSUE TITLE
Most of the time is spent filling the factorial table

### ISSUE THREAD

**Issue by John-Colvin** [rillki/humble-benchmarks#8]
If you were expecting to call `fisherExact` many times, you'd be doing a lot of duplicate work. log factorials are such a key thing in stats that I would imagine a "log factorial store" that lazily caches the results, where you can ask for a slice of them or just one-by-one, plus options to clear the cache etc. would be really valuable for performance across a multitude of tasks.

```d
struct LogFactorialCache {
    private static double[] data;

    static void cacheTo(size_t n) {
        size_t oldLength = data.length;
        if (data.length <= n) {
            data.length = n + 1;
            if (oldLength == 0) {
                data[0] = 0;
                oldLength = 1;
            }
            foreach (i; oldLength .. n + 1) {
                data[i] = data[i - 1] + log(i);
            }
        }
    }

    // this is a rubbish function, because you'll never free
    // the memory. Needs redesign.
    static void shrinkTo(size_t n) {
        data.length = n + 1;
    }

    /// for one-off or non-contiguous usage,
    /// slight overhead per access
    static double opIndex(size_t i) {
        cacheTo(i);
        return data[i];
    }

    /// for when you know you want a block of them
    /// and want fast access inside.
    static double[] opSlice(size_t i0, size_t i1) {
        cacheTo(i1);
        return data[i0 .. i1];
    }
}
```

or something like that. Untested. Of course the same idea applies to other languages, not just D.

**Comment by rillki** [comment]
John, thank you for the idea and your help. 

`fisherExact` test is needed to test whether there is a dependence between the two variables. I doubt that it would be run more than a few times. So caching the log factorials is unnecessary here.
